### ISSUE TITLE
speech results

### ISSUE THREAD

**Issue by JeremyCCHsu** [twidddj/vqvae#1]
Hi, do you have any results on real speech (and maybe longer sequences up to 1 second)? I also implemented the VQ-VAE, but I had a hard time reproducing their result in speech. Their voice quality is insanely high. In the end, I didn't put my repo on Github.

BTW, I would like to contact you via email instead of opening an issue, but I didn't find any contact information on your profile.

**Comment by twidddj** [comment]
Hello, Jeremy. Thank you for your interest to my project. But sorry, I didn’t have enough resource to progress this project in these days.  I’ll mail you immediately when I have any result on voice conversion. See you soon!

**Comment by JeremyCCHsu** [comment]
Hopefully you'll figure that out. Wish the best of you. BTW, you can find my email in my profile.
